[package]
name = "algorithms"
version = "0.1.0"
authors = ["jmurray <john@gardenway.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
bench = false
path = "src/bin/dijkstra.rs"
name = "dijkstra"
